"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.rankingMap = void 0;
exports.rankingMap = new Map();
exports.rankingMap.set('Ranking Phase Name', 'RankingPhaseName');
exports.rankingMap.set('Start Date', 'StartDate');
exports.rankingMap.set('End Date', 'EndDate');
exports.rankingMap.set('TemplateName', 'TemplateName');
exports.rankingMap.set('Description', 'Description');
exports.rankingMap.set('Is Default Template', 'cstm_IsDefaultTemplate');
exports.rankingMap.set('Template Name', 'TemplateName');
exports.rankingMap.set('Ranking Evaluation Criteria', 'CriteriaItemName');
exports.rankingMap.set('Guidance for Evaluation', 'CriteriaItemGuidance');
exports.rankingMap.set('Min Score', 'MinScore');
exports.rankingMap.set('Max Score', 'MaxScore');
exports.rankingMap.set('Weight', 'Weight');
exports.rankingMap.set('Scenario', 'cstm_ScenarioId');
exports.rankingMap.set('Weighted Score', 'WeightedScore');
exports.rankingMap.set('Adjusted Score', 'txtActualScore');
exports.rankingMap.set('Overall Rank', 'OverallRank');
//# sourceMappingURL=RankingAttributes.js.map