/* eslint-disable unicorn/no-null */
import { BaseEntity } from './BaseEntity';

export const implementedProjectEntity: BaseEntity = {
    EntityName: 'implementedprojects',
    IsBulkEditStatus: false,
    Id: null,
    Name: null,
    TimeStamp: 0,
    Attributes: {
        ImplementedProjectAutoID: 0,
        ProjectID: 'AA1',
        ProjectName: 'AA1',
        DepartmentID: 29,
        DepartmentPriorityRanking: null,
        ProjectFullName: null,
        CreatedBy: null,
        ProjectManagerID: 0,
        ProjectDescription: null,
        UnderSchedule: 0,
        ProjectJustification: null,
        IntentOfProjectID: 0,
        ProjectTotalEncumbrance: 0,
        OtherIntentOfProject: null,
        ProjectTotalPendingExpense: 0,
        ProjectUsualTypeID: 0,
        AccountNumber: null,
        ProjectTotalExpense: null,
        ProgramID: 0,
        TotalRiskExposure: 0,
        ProjectExpenseBudgetRatio: null,
        SubProgramID: 1,
        CostRate: 0,
        ProposedProjectFunding: null,
        ContactPerson: null,
        HasProjectTracking: null,
        Phone: null,
        GeneralCategory: null,
        OperationImpact: null,
        OtherInfo: null,
        PageNumber: null,
        IsAnnualProject: null,
        StatusID: null,
        Notes: null,
        CreatedDate: null,
        EstimateInfo: null,
        DistrictID: 0,
        Address: null,
        ZipCode: null,
        ServiceDepartmentID: 0,
        ParentProjectAutoID: 0,
        OutlineCode: null,
        ProjectLocationName: null,
        ScheduleStatusID: 0,
        Completed: null,
        ImgUrl: null,
        CompletedDate: null,
        ProjectLocationNote: null,
        SystemProjectTypeID: 1,
        IsCloseOut: 0,
        ProjectProgressStatusAutoID: 0,
        CloseBy: null,
        CloseDate: null,
        ModifiedBy: null,
        ModifiedOn: null,
        CurrencyGuid: null,
        IsDeleted: 0,
        ApprovalStatusID: 1,
        ProjectTotalBudget: 0,
        ProjectTotalActualExpense: 0,
        cstm_Picklist: 0,
        cstm_ProjectPhase: 1,
        cstm_ProjectStatus: 8
    },
    Displays: {
        DepartmentID: 'CITY ATTORNEY',
        DepartmentPriorityRanking:'',
        CreatedBy:'',
        ProjectManagerID:'',
        IntentOfProjectID:'',
        ProjectUsualTypeID:'',
        ProgramID:'',
        SubProgramID:'',
        HasProjectTracking:'',
        IsAnnualProject:'',
        DistrictID:'',
        ServiceDepartmentID:'',
        ParentProjectAutoID:'',
        ScheduleStatusID:'',
        SystemProjectTypeID:'',
        IsCloseOut: 'Open',
        ProjectProgressStatusAutoID:'',
        ModifiedBy:'',
        CurrencyGuid:'',
        IsDeleted: 'No',
        ApprovalStatusID:'',
        cstm_Picklist:'',
        cstm_ProjectPhase: 'Planning',
        cstm_ProjectStatus: 'Approved'
    },
    DeniedAttributes: [],
    ReadOnlyAttributes: [],
    Children: {},
    Association: {},
    Document: {},
    AccessType: 'Write',
    WF: {
        Enabled: false,
        IsRunning: false,
        RunAt: null
    },
    Workflow: null,
    Type: 'Formal',
    accessInfo: null,
    OriginalValues: null,
    ActionType:'A'
}