export const  scheduleAttributeMap = new Map()
scheduleAttributeMap.set('Schedule Name', 'ScheduleName')
scheduleAttributeMap.set('Calendar', 'CalendarAutoID')
scheduleAttributeMap.set('Status', 'ScheduleStatusID')
scheduleAttributeMap.set('Is Primary', 'IsPrimary')
scheduleAttributeMap.set('Schedule Status', 'ProgressStatusID')
scheduleAttributeMap.set('% Completed', 'Completed')
scheduleAttributeMap.set('Status Date', 'ProgressStatusDate')
scheduleAttributeMap.set('Schedule Start','BeginDate' )
scheduleAttributeMap.set('Schedule Finish', 'EndDate')
scheduleAttributeMap.set('Planned Start', 'PlannedStartDate')
scheduleAttributeMap.set('Planned Finish', 'PlannedFinishDate')
scheduleAttributeMap.set('Actual Start', 'ActualStartDate')
scheduleAttributeMap.set('Actual Finish', 'ActualFinishDate')
