export const CSOAttributeMap = new Map()
CSOAttributeMap.set('Category','IssueCategoryID')
CSOAttributeMap.set('Primary Project','PrimaryIprjAutoID')
CSOAttributeMap.set('Primary Contract','PrimaryContractAutoID')
CSOAttributeMap.set('ID', 'IssueID')
CSOAttributeMap.set('Title','Title')
CSOAttributeMap.set('Type','IssueTypeID')
CSOAttributeMap.set('Status','IssueStatusID')
CSOAttributeMap.set('Priority','IssuePriorityID')
CSOAttributeMap.set('Date Reported','DateReported')
CSOAttributeMap.set('Deadline','Deadline')
CSOAttributeMap.set('Submission Date','SubmissionDate')
CSOAttributeMap.set('Description','Description')
CSOAttributeMap.set('CSH ID', 'IssueID')

CSOAttributeMap.set('Project Name','ProjectName')
CSOAttributeMap.set('Contract Name','ContractName')