export const contractLineItemAttributesMap = new Map()
contractLineItemAttributesMap.set('Bid Specs No.', 'cstm_BidSpecsNo')
contractLineItemAttributesMap.set('SOV Item', 'SovItemAutoID')
contractLineItemAttributesMap.set('Type', 'LineItemType')
contractLineItemAttributesMap.set('(Sub-)Contractor', 'VendorAutoID')
contractLineItemAttributesMap.set('Unit', 'UnitID')
contractLineItemAttributesMap.set('Initial Unit Price', 'SourceUnitPrice')
contractLineItemAttributesMap.set('Initial Quantity', 'Quantity')
contractLineItemAttributesMap.set('Initial Amount', 'SourceAmount')
contractLineItemAttributesMap.set('Latest Unit Price', 'SourceLatestUnitPrice')
contractLineItemAttributesMap.set('Latest Quantity', 'LatestQuantity')
contractLineItemAttributesMap.set('Latest Amount', 'SourceLatestAmount')
contractLineItemAttributesMap.set('Completed', 'CompletedAmount')
contractLineItemAttributesMap.set('Invoiced Amount', 'InvoiceAmount')
contractLineItemAttributesMap.set('Remaining', 'Remaining')
contractLineItemAttributesMap.set('Paid Amount', 'Paid')
contractLineItemAttributesMap.set('Category', 'CategoryID') 
contractLineItemAttributesMap.set('Contract Cost Type', 'ContractCostTypeID') 


// Contract Line Item Splits
contractLineItemAttributesMap.set('Project', 'ImplementedProjectAutoID')
contractLineItemAttributesMap.set('Fund', 'FundID')
contractLineItemAttributesMap.set('Percentage', 'Percentage')
contractLineItemAttributesMap.set('Amount', 'SourceAmount')
