export const designSubmittalAttributeMap = new Map()
designSubmittalAttributeMap.set('Category','IssueCategoryID')
designSubmittalAttributeMap.set('Primary Project','PrimaryIprjAutoID')
designSubmittalAttributeMap.set('Primary Contract','PrimaryContractAutoID')
designSubmittalAttributeMap.set('Title','Title')
designSubmittalAttributeMap.set('Type','IssueTypeID')
designSubmittalAttributeMap.set('Status','IssueStatusID')
designSubmittalAttributeMap.set('Priority','IssuePriorityID')
designSubmittalAttributeMap.set('Date Reported','DateReported')
designSubmittalAttributeMap.set('Deadline','Deadline')
designSubmittalAttributeMap.set('Submission Date','SubmissionDate')
designSubmittalAttributeMap.set('Description','Description')
designSubmittalAttributeMap.set('Submittal ID', 'cstm_SubmittalID')

designSubmittalAttributeMap.set('Project Name','ProjectName')
designSubmittalAttributeMap.set('Contract Name','ContractName')