"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CSOAttributeMap = void 0;
exports.CSOAttributeMap = new Map();
exports.CSOAttributeMap.set('Category', 'IssueCategoryID');
exports.CSOAttributeMap.set('Primary Project', 'PrimaryIprjAutoID');
exports.CSOAttributeMap.set('Primary Contract', 'PrimaryContractAutoID');
exports.CSOAttributeMap.set('ID', 'IssueID');
exports.CSOAttributeMap.set('Title', 'Title');
exports.CSOAttributeMap.set('Type', 'IssueTypeID');
exports.CSOAttributeMap.set('Status', 'IssueStatusID');
exports.CSOAttributeMap.set('Priority', 'IssuePriorityID');
exports.CSOAttributeMap.set('Date Reported', 'DateReported');
exports.CSOAttributeMap.set('Deadline', 'Deadline');
exports.CSOAttributeMap.set('Submission Date', 'SubmissionDate');
exports.CSOAttributeMap.set('Description', 'Description');
exports.CSOAttributeMap.set('CSH ID', 'IssueID');
exports.CSOAttributeMap.set('Project Name', 'ProjectName');
exports.CSOAttributeMap.set('Contract Name', 'ContractName');
//# sourceMappingURL=CSOAttributes.js.map