"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.projectAttributesMap = void 0;
exports.projectAttributesMap = new Map();
exports.projectAttributesMap.set('Cycle', 'CycleID');
exports.projectAttributesMap.set('Scenario', 'ScenarioID');
exports.projectAttributesMap.set('Project ID', 'ProjectID');
exports.projectAttributesMap.set('Project', 'ProjectName');
exports.projectAttributesMap.set('Program', 'ProgramID');
exports.projectAttributesMap.set('Subprogram', 'SubProgramID');
exports.projectAttributesMap.set('Department', 'DepartmentID');
exports.projectAttributesMap.set('Project Manager', 'ProjectManagerID');
exports.projectAttributesMap.set('District', 'DistrictID');
exports.projectAttributesMap.set('Project Intent', 'IntentOfProjectID');
exports.projectAttributesMap.set('Funding Status', 'IsFunded');
exports.projectAttributesMap.set('Implementation Status', 'StatusID');
exports.projectAttributesMap.set('Project Type', 'ProjectStatus');
exports.projectAttributesMap.set('Account Number', 'AccountNumber');
exports.projectAttributesMap.set('Master Project', 'ParentProjectAutoID');
exports.projectAttributesMap.set('Is Annual Project', 'IsAnnualProject');
exports.projectAttributesMap.set('Primary Fund Group', 'PrimaryFundGroupID');
exports.projectAttributesMap.set('Service Department', 'ServiceDepartmentID');
exports.projectAttributesMap.set('Department Priority Ranking', 'DepartmentPriorityRanking');
exports.projectAttributesMap.set('Contact Person', 'ContactPerson');
exports.projectAttributesMap.set('Page Number', 'PageNumber');
exports.projectAttributesMap.set('Phone Number', 'Phone');
exports.projectAttributesMap.set('Project Location', 'ProjectLocation');
exports.projectAttributesMap.set('Location Description', 'LocationDescription');
exports.projectAttributesMap.set('Address', 'Address');
exports.projectAttributesMap.set('Zip Code', 'ZipCode');
exports.projectAttributesMap.set('Project Description', 'ProjectDescription');
exports.projectAttributesMap.set('Project Justification', 'ProjectJustification');
exports.projectAttributesMap.set('Operation Impact', 'OperationImpact');
exports.projectAttributesMap.set('Other Information', 'OtherInfo');
exports.projectAttributesMap.set('Proposed Project Funding', 'ProposedProjectFunding');
exports.projectAttributesMap.set('Fund Group ID', 'GroupID');
exports.projectAttributesMap.set('Currency', 'CurrencyGuid');
exports.projectAttributesMap.set('Resource ID', 'ResourceID');
exports.projectAttributesMap.set('Resource Name', 'ResourceName');
exports.projectAttributesMap.set('Open/Closed Status', 'IsCloseOut');
exports.projectAttributesMap.set('Project Status', 'cstm_ProjectStatus');
exports.projectAttributesMap.set('Project Phase', 'cstm_ProjectPhase');
/**********************copy selected project 弹窗********************* */
exports.projectAttributesMap.set('Cycle1', 'DestinationCycle');
exports.projectAttributesMap.set('Scenario1', 'DestinationScenario');
//# sourceMappingURL=ProjectAttributes.js.map