"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.contractAttributesMap = void 0;
exports.contractAttributesMap = new Map();
exports.contractAttributesMap.set('Contract Type', 'ContractTypeOfService');
exports.contractAttributesMap.set('Contract No.', 'ContractID');
exports.contractAttributesMap.set('Contract Name', 'ContractName');
exports.contractAttributesMap.set('Prime Contractor', 'VendorAutoID');
exports.contractAttributesMap.set('Contract Status', 'ContractStatusID');
exports.contractAttributesMap.set('Award Date', 'AwardDate');
exports.contractAttributesMap.set('Signed Date', 'SignedDate');
exports.contractAttributesMap.set('NTP Date', 'NTPDate');
exports.contractAttributesMap.set('Substantial Completion Date', 'SubstantialCompletionDate');
exports.contractAttributesMap.set('Final Completion Date', 'FinalCompletionDate');
exports.contractAttributesMap.set('Contact Person', 'ContractPerson');
exports.contractAttributesMap.set('Description', 'Description');
exports.contractAttributesMap.set('Contract Total Amount', 'CtrTotalAmtParentPlusSub');
exports.contractAttributesMap.set('DBE Participation Goal', 'DBEParticipationGoal');
exports.contractAttributesMap.set('Retainage Rate', 'RetainageRate');
exports.contractAttributesMap.set('Maximum Retainage Percentage', 'MaxRetainageRate');
exports.contractAttributesMap.set('Start Date', 'BeginDate');
exports.contractAttributesMap.set('Duration', 'Duration');
exports.contractAttributesMap.set('End Date', 'EndDate');
exports.contractAttributesMap.set('Start Date', 'BeginDate');
exports.contractAttributesMap.set('Parent Contract', 'ParentContractAutoID');
exports.contractAttributesMap.set('Vendor ID', 'VendorID');
exports.contractAttributesMap.set('Project Name', 'ProjectName');
exports.contractAttributesMap.set('Fund ID', 'FundID');
//# sourceMappingURL=ContractAttributes.js.map