"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.invoiceAttributeMap = void 0;
exports.invoiceAttributeMap = new Map();
exports.invoiceAttributeMap.set('Contract', 'ContractPicker');
exports.invoiceAttributeMap.set('Purchase Order', 'POPicker');
exports.invoiceAttributeMap.set('Vendor', 'VendorPicker');
exports.invoiceAttributeMap.set('Type of Service', 'TypeOfService');
exports.invoiceAttributeMap.set('Invoice No.', 'InvoiceNumber');
exports.invoiceAttributeMap.set('Invoice Date', 'InvoiceDate');
exports.invoiceAttributeMap.set('Invoice Status', 'InvoiceStatusID');
exports.invoiceAttributeMap.set('Billing Period From', 'BillPeriodFrom');
exports.invoiceAttributeMap.set('Billing Period To', 'BillPeriodTo');
exports.invoiceAttributeMap.set('Payment Due Date', 'PaymentDueDate');
exports.invoiceAttributeMap.set('Vendor Address', 'VendorAddress');
exports.invoiceAttributeMap.set('Billing Address', 'BillingAddress');
exports.invoiceAttributeMap.set('Description', 'Description');
exports.invoiceAttributeMap.set('Invoice Total Amount', 'InvoiceTotalAmount');
exports.invoiceAttributeMap.set('Default Retainage Rate', 'RetainageRate');
exports.invoiceAttributeMap.set('Invoice Total Amount Less Retainage', 'TotalAmountLessRetainage');
exports.invoiceAttributeMap.set('Inspection Reports', 'ucXEntityListBox');
exports.invoiceAttributeMap.set('Contract No.', 'ContractID');
exports.invoiceAttributeMap.set('Purchase Order Name', 'PurchaseOrderName');
exports.invoiceAttributeMap.set('Vendor ID', 'VendorID');
exports.invoiceAttributeMap.set('Report No.', 'ReportNumber');
//# sourceMappingURL=InvoiceAttributes.js.map