export const CSPAttributeMap = new Map()
CSPAttributeMap.set('Category','IssueCategoryID')
CSPAttributeMap.set('Primary Project','PrimaryIprjAutoID')
CSPAttributeMap.set('Primary Contract','PrimaryContractAutoID')
CSPAttributeMap.set('ID', 'IssueID')
CSPAttributeMap.set('Title','Title')
CSPAttributeMap.set('Type','IssueTypeID')
CSPAttributeMap.set('Status','IssueStatusID')
CSPAttributeMap.set('Priority','IssuePriorityID')
CSPAttributeMap.set('Date Reported','DateReported')
CSPAttributeMap.set('Deadline','Deadline')
CSPAttributeMap.set('Submission Date','SubmissionDate')
CSPAttributeMap.set('Description','Description')
CSPAttributeMap.set('CSH ID', 'IssueID')

CSPAttributeMap.set('Project Name','ProjectName')
CSPAttributeMap.set('Contract Name','ContractName')