export const documentAttributeMap = new Map()
documentAttributeMap.set('Version', 'Version')
documentAttributeMap.set('Status', 'StatusID')
documentAttributeMap.set('Key Words', 'KeyWords')
documentAttributeMap.set('Description', 'Description')
documentAttributeMap.set('Document ID:', 'FileAutoID')
documentAttributeMap.set('Document Name', 'FileDisplayName')
documentAttributeMap.set('Checked Out By', 'Checked Out By')
documentAttributeMap.set('Checked Out On', 'CheckOutOn')
documentAttributeMap.set('IsIndexed', 'IsIndexed')
documentAttributeMap.set('Entity', 'Entity')
documentAttributeMap.set('Created By', 'OwnerUserID')
documentAttributeMap.set('Is Checked Out', 'FileStatusID')
documentAttributeMap.set('Last Modified Time', 'Last Modified Time')
documentAttributeMap.set('Full-text search', 'txtFullText')

