export const invoiceAttributeMap = new Map()
invoiceAttributeMap.set('Contract', 'ContractPicker')
invoiceAttributeMap.set('Purchase Order', 'POPicker')
invoiceAttributeMap.set('Vendor', 'VendorPicker')
invoiceAttributeMap.set('Type of Service', 'TypeOfService')
invoiceAttributeMap.set('MUNIS Invoice Number', 'cstm_InvoiceNumber')
invoiceAttributeMap.set('Invoice Date', 'InvoiceDate')
invoiceAttributeMap.set('Invoice Status', 'InvoiceStatusID')
invoiceAttributeMap.set('Billing Period From', 'BillPeriodFrom')
invoiceAttributeMap.set('Billing Period To', 'BillPeriodTo')
invoiceAttributeMap.set('Payment Due Date','PaymentDueDate')
invoiceAttributeMap.set('Vendor Address', 'VendorAddress')
invoiceAttributeMap.set('Billing Address', 'BillingAddress')
invoiceAttributeMap.set('Description', 'Description')
invoiceAttributeMap.set('Invoice Total Amount', 'InvoiceTotalAmount')
invoiceAttributeMap.set('Default Retainage Rate','RetainageRate')
invoiceAttributeMap.set('Invoice Total Amount Less Retainage', 'TotalAmountLessRetainage')
invoiceAttributeMap.set('Inspection Reports', 'ucXEntityListBox')
invoiceAttributeMap.set('Invoice ID', 'InvoiceNumber')

invoiceAttributeMap.set('Contract Name', 'ContractName')
invoiceAttributeMap.set('Purchase Order Name', 'PurchaseOrderName')
invoiceAttributeMap.set('Vendor ID', 'VendorID')
invoiceAttributeMap.set('Report No.', 'ReportNumber')


