"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.pageMap = exports.PROJECT_URL = void 0;
const DefaultStaticParams_1 = require("../DefaultStaticParams");
const StaticPageName_1 = require("./common/statics/StaticPageName");
// 项目地址
exports.PROJECT_URL = '/DailyBuild';
// export const PROJECT_URL ='/r20231228'
/**
 * 设置页面名称与对应url的键值对
 * eg: pageMap.set("页面名称", "页面除去前缀之后的url")
 */
exports.pageMap = new Map();
exports.pageMap.set(DefaultStaticParams_1.LOGIN, exports.PROJECT_URL + '/Users/Login.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_CONTRACTS, exports.PROJECT_URL + '/Contract/BrowseContracts.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_VENDERS, exports.PROJECT_URL + '/Vendors/BrowseVendors.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_PROJECTS, exports.PROJECT_URL + '/Projects/BrowsePlanningProjects.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_FUNDS, exports.PROJECT_URL + '/Funds/BrowseFunds.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_BUDGET, exports.PROJECT_URL + '/Budget/BrowseBudget.aspx');
exports.pageMap.set(StaticPageName_1.ADD_CONTRACT, exports.PROJECT_URL + '/Contract/ContractManagement.aspx');
exports.pageMap.set(StaticPageName_1.ADD_CONTRACT_INVOICE, exports.PROJECT_URL + '/Invoices/ManageInvoices.aspx?InvoiceFinancialStructure=3');
exports.pageMap.set(StaticPageName_1.ADD_PO_INVOICE, exports.PROJECT_URL + '/Invoices/ManageInvoices.aspx?InvoiceFinancialStructure=2');
exports.pageMap.set(StaticPageName_1.ADD_INVOICE_ONLY, exports.PROJECT_URL + '/Invoices/ManageInvoices.aspx?InvoiceFinancialStructure=4');
exports.pageMap.set(StaticPageName_1.ADD_CONTRACT_INSPECTION_INVOICE, exports.PROJECT_URL + '/Invoices/ManageInvoices.aspx?InvoiceFinancialStructure=5');
exports.pageMap.set(StaticPageName_1.BROWSE_INVOICES, exports.PROJECT_URL + '/Invoices/BrowseInvoices.aspx');
exports.pageMap.set(StaticPageName_1.SAVE_SCOPINGGENERAL, exports.PROJECT_URL + '/Evaluation/ProjectEvaluationNew.aspx?ScopingProjectScenarioID=57&ScopingAreaID=1&ProjectAutoID=54');
exports.pageMap.set(StaticPageName_1.SAVE_SCOPINGFINANCIAL, exports.PROJECT_URL + '/Evaluation/ProjectEvaluationNew.aspx?ScopingProjectScenarioID=57&ScopingAreaID=2&ProjectAutoID=54');
exports.pageMap.set(StaticPageName_1.SAVE_SCOPINGENVIRONMENT, exports.PROJECT_URL + '/Evaluation/ProjectEvaluationNew.aspx?ScopingProjectScenarioID=57&ScopingAreaID=3&ProjectAutoID=54');
exports.pageMap.set(StaticPageName_1.SAVE_SCOPINGPUBLICSAFETY, exports.PROJECT_URL + '/Evaluation/ProjectEvaluationNew.aspx?ScopingProjectScenarioID=57&ScopingAreaID=4&ProjectAutoID=54');
exports.pageMap.set(StaticPageName_1.SAVE_SCOPINGFINANCIALDETAIL, exports.PROJECT_URL + '/Evaluation/ProjectEvaluationNew.aspx?ScopingProjectScenarioID=57&ScopingAreaID=2&ProjectAutoID=54&ViewDetail=1');
exports.pageMap.set(StaticPageName_1.BROWSE_SOLICITATIONS, exports.PROJECT_URL + '/BidManagement/BrowseSol.aspx');
exports.pageMap.set(StaticPageName_1.ADD_SOLICITATION, exports.PROJECT_URL + '/BidManagement/SolGeneralManagement.aspx');
exports.pageMap.set(StaticPageName_1.MANAGE_SOLICITATION, exports.PROJECT_URL + '/BidManagement/SolGeneralManagement.aspx');
exports.pageMap.set(StaticPageName_1.ADD_VENDOR, exports.PROJECT_URL + '/Vendors/EditVendor.aspx');
exports.pageMap.set(StaticPageName_1.ADD_DOCUMENT, exports.PROJECT_URL + '/DocManagement/DocFileDetails.aspx?Act=New');
exports.pageMap.set(StaticPageName_1.BROWSE_DOCUMENTS, exports.PROJECT_URL + '/DocManagement/DocSearch.aspx');
exports.pageMap.set(StaticPageName_1.ADD_COR, exports.PROJECT_URL + '/ChangeOrder/CORManagement.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_COR, exports.PROJECT_URL + '/ChangeOrder/BrowseChangeOrderRequests.aspx');
exports.pageMap.set(StaticPageName_1.ADD_PROJECT, exports.PROJECT_URL + '/Projects/ProjectGeneral.aspx');
exports.pageMap.set(StaticPageName_1.ADD_IMPLEMENTATION_PROJECT, exports.PROJECT_URL + '/Projects/ImplementedProjectGeneral.aspx?Exist=1&ProjectType=2');
exports.pageMap.set(StaticPageName_1.BROWSE_IMPLEMENTATION_PROJECT, exports.PROJECT_URL + '/Projects/BrowseImplementationProjects.aspx');
exports.pageMap.set(StaticPageName_1.SCOPINGAREA_MANAGEMENT, exports.PROJECT_URL + '/Evaluation/ScopingAreaManagement.aspx');
exports.pageMap.set(StaticPageName_1.ADD_PUBLICPROPOSAL, exports.PROJECT_URL + '/Proposals/PublicProposal.aspx');
exports.pageMap.set(StaticPageName_1.ADD_STAFFPROPOSAL, exports.PROJECT_URL + '/Proposals/StaffProposalGeneral.aspx');
exports.pageMap.set(StaticPageName_1.ADD_RANKINGPHASE, exports.PROJECT_URL + '/Ranking/RankingPhaseManagement.aspx');
exports.pageMap.set(StaticPageName_1.ADD_FILTERINGPHASE, exports.PROJECT_URL + '/FilteringPhase/FilteringPhase.aspx');
exports.pageMap.set(StaticPageName_1.ADD_CHANGE_ORDER, exports.PROJECT_URL + '/ChangeOrder/ChangeOrderManagement.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_CHANGE_ORDERS, exports.PROJECT_URL + '//ChangeOrder/BrowseChangeOrders.aspx');
exports.pageMap.set(StaticPageName_1.ADD_ISSUE, exports.PROJECT_URL + '/Issues/IssueGeneric.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_ISSUES, exports.PROJECT_URL + 'Issues/browseobjects.aspx?entityname=issuesgeneric');
exports.pageMap.set(StaticPageName_1.ADD_CSH, exports.PROJECT_URL + '/Issues/ObjectManagement.aspx?entityname=constructschd');
exports.pageMap.set(StaticPageName_1.BROWSE_CSH, exports.PROJECT_URL + '/Issues/BrowseObjects.aspx?EntityName=constructschd');
exports.pageMap.set(StaticPageName_1.ADD_CPS, exports.PROJECT_URL + '/Issues/ObjectManagement.aspx?EntityName=productsubmt');
exports.pageMap.set(StaticPageName_1.BROWSE_CPS, exports.PROJECT_URL + '/Issues/BrowseObjects.aspx?EntityName=Productsubmt');
exports.pageMap.set(StaticPageName_1.BROWSE_CHANGE_ORDERS, exports.PROJECT_URL + '//ChangeOrder/BrowseChangeOrders.aspx');
exports.pageMap.set(StaticPageName_1.ADD_REQUESTFORPROPOSAL, exports.PROJECT_URL + '/ChangeOrder/RFPManagement.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_REQUESTFORPROPOSAL, exports.PROJECT_URL + '/ChangeOrder/BrowseRequestForProposals.aspx');
exports.pageMap.set(StaticPageName_1.ADD_CSP, exports.PROJECT_URL + '/Issues/ObjectManagement.aspx?entityname=Safetyplan');
exports.pageMap.set(StaticPageName_1.BROWSE_CSP, exports.PROJECT_URL + '/Issues/browseobjects.aspx?entityname=Safetyplan');
exports.pageMap.set(StaticPageName_1.ADD_CSO, exports.PROJECT_URL + '/Issues/ObjectManagement.aspx?entityname=Othcttsubmt');
exports.pageMap.set(StaticPageName_1.BROWSE_CSO, exports.PROJECT_URL + '/Issues/browseobjects.aspx?entityname=Othcttsubmt');
exports.pageMap.set(StaticPageName_1.ADD_ODS, exports.PROJECT_URL + '/Issues/ObjectManagement.aspx?EntityName=othdsnsubmt');
exports.pageMap.set(StaticPageName_1.BROWSE_ODS, exports.PROJECT_URL + '/Issues/BrowseObjects.aspx?EntityName=othdsnsubmt');
exports.pageMap.set(StaticPageName_1.BROWSE_DESIGN_REVIEW, exports.PROJECT_URL + '/Issues/BrowseObjects.aspx?EntityName=DesignReview');
exports.pageMap.set(StaticPageName_1.ADD_DESIGN_REVIEW, exports.PROJECT_URL + '/Issues/ObjectManagement.aspx?EntityName=designreview');
exports.pageMap.set(StaticPageName_1.ADD_RISK, exports.PROJECT_URL + '/Risks/RiskMan.aspx');
exports.pageMap.set(StaticPageName_1.ADD_USER, exports.PROJECT_URL + '/Users/Users.aspx');
exports.pageMap.set(StaticPageName_1.ADD_CYCLE, exports.PROJECT_URL + '/Util/CycleMan.aspx');
exports.pageMap.set(StaticPageName_1.ADD_SCENARIO, exports.PROJECT_URL + '/Util/ScenarioMan.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_CYCLES, exports.PROJECT_URL + '/Util/BrowseCycles.aspx');
exports.pageMap.set(StaticPageName_1.ADD_ASSIGNMENT, exports.PROJECT_URL + '/Contract/InspectionAssignmentGeneral.aspx');
exports.pageMap.set(StaticPageName_1.ADD_INSPECTIONREPORT, exports.PROJECT_URL + '/Contract/InspectionReportManagement.aspx');
exports.pageMap.set(StaticPageName_1.ADD_FUNDGROUP, exports.PROJECT_URL + '/Funds/GroupMan.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_FUNDGROUP, exports.PROJECT_URL + '/Funds/BrowseGroups.aspx');
exports.pageMap.set(StaticPageName_1.ADD_ASSET, exports.PROJECT_URL + '/Assets/AssetMan.aspx');
exports.pageMap.set(StaticPageName_1.ADD_WO, exports.PROJECT_URL + '/Assets/ViewAssetMantenance.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_ASSET, exports.PROJECT_URL + '/Assets/BrowseAssetInTree.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_WO, exports.PROJECT_URL + '/Assets/MaintenancePlan.aspx');
exports.pageMap.set(StaticPageName_1.ADD_BULLETIN, exports.PROJECT_URL + '/Issues/BulletinManagement.aspx');
exports.pageMap.set(StaticPageName_1.ADD_DSI, exports.PROJECT_URL + '/Issues/DSIManagement.aspx');
exports.pageMap.set(StaticPageName_1.ADD_RFI, exports.PROJECT_URL + '/Issues/IssueRFI.aspx');
exports.pageMap.set(StaticPageName_1.ADD_SA, exports.PROJECT_URL + '/Issues/ObjectManagement.aspx?EntityName=studyanalysis');
exports.pageMap.set(StaticPageName_1.ADD_MEETING, exports.PROJECT_URL + '/MeetingMinutes/MeetingMinutesManagement.aspx');
exports.pageMap.set(StaticPageName_1.ADD_PERMIT, exports.PROJECT_URL + '/Permits/PermitsManagement.aspx');
exports.pageMap.set(StaticPageName_1.ADD_TIMESHEET, exports.PROJECT_URL + '/TimeSheets/ManageTimeSheet.aspx');
exports.pageMap.set(StaticPageName_1.ADD_TRANSFER, exports.PROJECT_URL + '/Transfer/TransferManagement.aspx');
exports.pageMap.set(StaticPageName_1.BROWSE_ASSIGNMENT, exports.PROJECT_URL + '/Contract/BrowseInspectionAssignment.aspx');
//# sourceMappingURL=WebsitePageMap.js.map