export const invoiceAttributeMap = new Map()
invoiceAttributeMap.set('Contract', 'ContractPicker')
invoiceAttributeMap.set('Purchase Order', 'POPicker')
invoiceAttributeMap.set('Vendor', 'VendorPicker')
invoiceAttributeMap.set('Type of Service', 'TypeOfService')
invoiceAttributeMap.set('Invoice No.', 'InvoiceNumber')
invoiceAttributeMap.set('Invoice Date', 'InvoiceDate')
invoiceAttributeMap.set('Invoice Status', 'InvoiceStatusID')
invoiceAttributeMap.set('Billing Period From', 'BillPeriodFrom')
invoiceAttributeMap.set('Billing Period To', 'BillPeriodTo')
invoiceAttributeMap.set('Payment Due Date','PaymentDueDate')
invoiceAttributeMap.set('Vendor Address', 'VendorAddress')
invoiceAttributeMap.set('Billing Address', 'BillingAddress')
invoiceAttributeMap.set('Description', 'Description')
invoiceAttributeMap.set('Invoice Total Amount', 'InvoiceTotalAmount')
invoiceAttributeMap.set('Default Retainage Rate','RetainageRate')
invoiceAttributeMap.set('Invoice Total Amount Less Retainage', 'TotalAmountLessRetainage')
invoiceAttributeMap.set('Inspection Reports', 'ucXEntityListBox')

invoiceAttributeMap.set('Contract No.', 'ContractID')
invoiceAttributeMap.set('Purchase Order Name', 'PurchaseOrderName')
invoiceAttributeMap.set('Vendor ID', 'VendorID')
invoiceAttributeMap.set('Report No.', 'ReportNumber')


