"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.issueAttributeMap = void 0;
exports.issueAttributeMap = new Map();
exports.issueAttributeMap.set('Category', 'IssueCategoryID');
exports.issueAttributeMap.set('Issue ID', 'IssueID');
exports.issueAttributeMap.set('Issue Title', 'Title');
exports.issueAttributeMap.set('Status', 'IssueStatusID');
exports.issueAttributeMap.set('Priority', 'IssuePriorityID');
exports.issueAttributeMap.set('Date Reported', 'DateReported');
exports.issueAttributeMap.set('Deadline', 'Deadline');
exports.issueAttributeMap.set('Submission Date', 'SubmissionDate');
exports.issueAttributeMap.set('Description', 'Description');
exports.issueAttributeMap.set('Project', 'cstm_AssociatedProjectId');
exports.issueAttributeMap.set('Contract', 'cstm_AssociatedContractId');
exports.issueAttributeMap.set('Project Name', 'ProjectName');
exports.issueAttributeMap.set('Contract Name', 'ContractName');
exports.issueAttributeMap.set('Assigned Reviewers', 'RelationshipFieldFK_resources_issueresourcesassignedto_issuesgeneric');
exports.issueAttributeMap.set('Resource ID', 'ResourceID');
//# sourceMappingURL=IssueAttributes.js.map