export const addResourceAttributeMap = new Map()
addResourceAttributeMap.set('Resource ID','resources-resourceid')
addResourceAttributeMap.set('Resource Name','resources-resourcename1')
addResourceAttributeMap.set('Resource Type', 'resources-resourcetypeid1')
addResourceAttributeMap.set('Status','resources-isactive1')