export const COAttributeMap = new Map()
COAttributeMap.set('Primary Project', 'PImpProjAutoID')
COAttributeMap.set('Primary Contract', 'PContractAutoID')
COAttributeMap.set('Issue Date', 'IssueDate')
COAttributeMap.set('Contractor', 'VendorAutoID')
COAttributeMap.set('Status', 'StatusID')
COAttributeMap.set('Contact Name','ContactName' )
COAttributeMap.set('Authorization Status Date', 'AuthorizationStatusDate')
COAttributeMap.set('CO ID','ChangeNumber')
COAttributeMap.set('Subject', 'SubjectDesc')
COAttributeMap.set('Reason of Change','ReasonOfChange')
COAttributeMap.set('Description of Change', 'DescriptionOfChange')


COAttributeMap.set('Project Name', 'ProjectName')
COAttributeMap.set('Contract Name', 'ContractName')
COAttributeMap.set('Vendor ID', 'VendorID')
