export const CPSAttributeMap = new Map()
CPSAttributeMap.set('Category','IssueCategoryID')
CPSAttributeMap.set('Primary Project','PrimaryIprjAutoID')
CPSAttributeMap.set('Primary Contract','PrimaryContractAutoID')
CPSAttributeMap.set('ID', 'IssueID')
CPSAttributeMap.set('Title','Title')
CPSAttributeMap.set('Type','IssueTypeID')
CPSAttributeMap.set('Status','IssueStatusID')
CPSAttributeMap.set('Priority','IssuePriorityID')
CPSAttributeMap.set('Date Reported','DateReported')
CPSAttributeMap.set('Deadline','Deadline')
CPSAttributeMap.set('Submission Date','SubmissionDate')
CPSAttributeMap.set('Description','Description')
CPSAttributeMap.set('CSH ID', 'IssueID')

CPSAttributeMap.set('Project Name','ProjectName')
CPSAttributeMap.set('Contract Name','ContractName')