"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DesignReviewAttributeMap = void 0;
exports.DesignReviewAttributeMap = new Map();
exports.DesignReviewAttributeMap.set('Category', 'IssueCategoryID');
exports.DesignReviewAttributeMap.set('Primary Project', 'PrimaryIprjAutoID');
exports.DesignReviewAttributeMap.set('Primary Contract', 'PrimaryContractAutoID');
exports.DesignReviewAttributeMap.set('ID', 'IssueID');
exports.DesignReviewAttributeMap.set('Title', 'Title');
exports.DesignReviewAttributeMap.set('Type', 'IssueTypeID');
exports.DesignReviewAttributeMap.set('Status', 'IssueStatusID');
exports.DesignReviewAttributeMap.set('Priority', 'IssuePriorityID');
exports.DesignReviewAttributeMap.set('Date Reported', 'DateReported');
exports.DesignReviewAttributeMap.set('Deadline', 'Deadline');
exports.DesignReviewAttributeMap.set('Submission Date', 'SubmissionDate');
exports.DesignReviewAttributeMap.set('Description', 'Description');
exports.DesignReviewAttributeMap.set('DRV ID', 'IssueID');
exports.DesignReviewAttributeMap.set('Project Name', 'ProjectName');
exports.DesignReviewAttributeMap.set('Contract Name', 'ContractName');
//# sourceMappingURL=DesignReviewAttributes.js.map