export const DesignReviewAttributeMap = new Map()
DesignReviewAttributeMap.set('Category','IssueCategoryID')
DesignReviewAttributeMap.set('Primary Project','PrimaryIprjAutoID')
DesignReviewAttributeMap.set('Primary Contract','PrimaryContractAutoID')
DesignReviewAttributeMap.set('ID', 'IssueID')
DesignReviewAttributeMap.set('Title','Title')
DesignReviewAttributeMap.set('Type','IssueTypeID')
DesignReviewAttributeMap.set('Status','IssueStatusID')
DesignReviewAttributeMap.set('Priority','IssuePriorityID')
DesignReviewAttributeMap.set('Date Reported','DateReported')
DesignReviewAttributeMap.set('Deadline','Deadline')
DesignReviewAttributeMap.set('Submission Date','SubmissionDate')
DesignReviewAttributeMap.set('Description','Description')
DesignReviewAttributeMap.set('DRV ID', 'IssueID')

DesignReviewAttributeMap.set('Project Name','ProjectName')
DesignReviewAttributeMap.set('Contract Name','ContractName')