"use strict";
/* eslint-disable unicorn/prevent-abbreviations */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SAVE_CONTINUE = exports.ADDSCOPINGAREA = exports.AddNewLineItems = exports.DELETE_PARENT_ONLY = exports.ADD_SUB_PROJECT = exports.ADD_MASTER_PROJECT = exports.POPUP = exports.DRAG = exports.PAY = exports.BATCH_UPDATE = exports.INSERT = exports.RESET = exports.GENERIC_EXPORT = exports.GENERIC_IMPORT = exports.DATA_EXPORT = exports.DATA_IMPORT = exports.DISASSOCIATE = exports.ASSOCIATE = exports.BATCH_DELETE = exports.LOAD_FROM = exports.LOGOUT = exports.LOGIN = exports.CANCEL = exports.OK = exports.SEARCH = exports.EDIT = exports.DELETE = exports.SAVE = exports.ADD = exports.FAILED = exports.SUCCEEDED = void 0;
exports.SUCCEEDED = 'succeeded';
exports.FAILED = 'failed';
exports.ADD = 'Add';
exports.SAVE = 'Save';
exports.DELETE = 'Delete';
exports.EDIT = 'Edit';
exports.SEARCH = 'Search';
exports.OK = 'OK';
exports.CANCEL = 'Cancel';
exports.LOGIN = 'Login';
exports.LOGOUT = 'Log Out';
exports.LOAD_FROM = 'Load From';
exports.BATCH_DELETE = 'Batch Delete';
exports.ASSOCIATE = 'Associate';
exports.DISASSOCIATE = 'Disassociate';
exports.DATA_IMPORT = 'Import';
exports.DATA_EXPORT = 'Export';
exports.GENERIC_IMPORT = 'Generic Import';
exports.GENERIC_EXPORT = 'Generic Export';
exports.RESET = 'Reset';
exports.INSERT = 'Insert';
exports.BATCH_UPDATE = 'Batch Update';
exports.PAY = 'Pay';
exports.DRAG = 'Drag To Move';
exports.POPUP = 'Popup to Edit';
exports.ADD_MASTER_PROJECT = 'Add Master Project';
exports.ADD_SUB_PROJECT = 'Add Sub Project';
exports.DELETE_PARENT_ONLY = 'Delete Parent Only';
exports.AddNewLineItems = 'Add New Line Items';
exports.ADDSCOPINGAREA = 'Add Scoping Area';
exports.SAVE_CONTINUE = 'Save & Continue';
//# sourceMappingURL=DefaultStaticParams.js.map