export const scopingTemplateAttributesMap = new Map()
scopingTemplateAttributesMap.set('Template Name','TemplateName')
scopingTemplateAttributesMap.set('Description','Notes')
scopingTemplateAttributesMap.set('Applicable Financial Type', 'FinancialType')
scopingTemplateAttributesMap.set('Period Option', 'PeriodOption')
scopingTemplateAttributesMap.set('Cost Scoping Methodology', 'lMethod')
scopingTemplateAttributesMap.set('Freezing Columns to the Left','FreezingColumns')
scopingTemplateAttributesMap.set('Cost Scoping Base Period','PeriodType')
scopingTemplateAttributesMap.set('Period Type', 'PeriodType')

scopingTemplateAttributesMap.set('Attribute', 'lblClassificationName')
scopingTemplateAttributesMap.set('Is Required', 'chkIsRequired')
scopingTemplateAttributesMap.set('Width', 'txtWidth')
scopingTemplateAttributesMap.set('Node', 'lblNode')