export const projectAttributesMap = new Map()
projectAttributesMap.set('Cycle', 'CycleID')
projectAttributesMap.set('Scenario','ScenarioID' )
projectAttributesMap.set('Project ID', 'ProjectID')
projectAttributesMap.set('Project', 'ProjectName')
projectAttributesMap.set('Program', 'ProgramID')
projectAttributesMap.set('Subprogram', 'SubProgramID')
projectAttributesMap.set('Department','DepartmentID' )
projectAttributesMap.set('Project Manager', 'ProjectManagerID')
projectAttributesMap.set('District', 'DistrictID')
projectAttributesMap.set('Project Intent', 'IntentOfProjectID')
projectAttributesMap.set('Funding Status', 'IsFunded')
projectAttributesMap.set('Implementation Status', 'StatusID')
projectAttributesMap.set('Project Type', 'ProjectStatus')
projectAttributesMap.set('Account Number', 'AccountNumber')


projectAttributesMap.set('Master Project', 'ParentProjectAutoID')
projectAttributesMap.set('Is Annual Project', 'IsAnnualProject')
projectAttributesMap.set('Primary Fund Group', 'PrimaryFundGroupID')
projectAttributesMap.set('Service Department', 'ServiceDepartmentID')
projectAttributesMap.set('Department Priority Ranking', 'DepartmentPriorityRanking')
projectAttributesMap.set('Contact Person', 'ContactPerson')
projectAttributesMap.set('Page Number', 'PageNumber')
projectAttributesMap.set('Phone Number', 'Phone')
projectAttributesMap.set('Project Location', 'ProjectLocation')
projectAttributesMap.set('Location Description', 'LocationDescription')
projectAttributesMap.set('Address', 'Address')
projectAttributesMap.set('Zip Code', 'ZipCode')
projectAttributesMap.set('Project Description', 'ProjectDescription')
projectAttributesMap.set('Project Justification', 'ProjectJustification')
projectAttributesMap.set('Operation Impact', 'OperationImpact')
projectAttributesMap.set('Other Information', 'OtherInfo')
projectAttributesMap.set('Proposed Project Funding', 'ProposedProjectFunding')
projectAttributesMap.set('Fund Group ID', 'GroupID')
projectAttributesMap.set('Currency', 'CurrencyGuid')
projectAttributesMap.set('Resource ID', 'ResourceID')
projectAttributesMap.set('Resource Name', 'ResourceName')

projectAttributesMap.set('Open/Closed Status', 'IsCloseOut')
projectAttributesMap.set('Project Status', 'cstm_ProjectStatus')
projectAttributesMap.set('Project Phase', 'cstm_ProjectPhase')

/**********************copy selected project 弹窗********************* */
projectAttributesMap.set('Cycle1', 'DestinationCycle')
projectAttributesMap.set('Scenario1', 'DestinationScenario')