export const issueAttributeMap =new Map()
issueAttributeMap.set('Category', 'IssueCategoryID')
issueAttributeMap.set('Issue ID', 'IssueID')
issueAttributeMap.set('Issue Title', 'Title')
issueAttributeMap.set('Status', 'IssueStatusID')
issueAttributeMap.set('Priority','IssuePriorityID')
issueAttributeMap.set('Date Reported', 'DateReported')
issueAttributeMap.set('Deadline','Deadline')
issueAttributeMap.set('Submission Date','SubmissionDate')
issueAttributeMap.set('Description','Description')
issueAttributeMap.set('Project','cstm_AssociatedProjectId')
issueAttributeMap.set('Contract','cstm_AssociatedContractId')
issueAttributeMap.set('Project Name','ProjectName')
issueAttributeMap.set('Contract Name','ContractName')
issueAttributeMap.set('Assigned Reviewers','RelationshipFieldFK_resources_issueresourcesassignedto_issuesgeneric')
issueAttributeMap.set('Resource ID','ResourceID')

