"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CPSAttributeMap = void 0;
exports.CPSAttributeMap = new Map();
exports.CPSAttributeMap.set('Category', 'IssueCategoryID');
exports.CPSAttributeMap.set('Primary Project', 'PrimaryIprjAutoID');
exports.CPSAttributeMap.set('Primary Contract', 'PrimaryContractAutoID');
exports.CPSAttributeMap.set('ID', 'IssueID');
exports.CPSAttributeMap.set('Title', 'Title');
exports.CPSAttributeMap.set('Type', 'IssueTypeID');
exports.CPSAttributeMap.set('Status', 'IssueStatusID');
exports.CPSAttributeMap.set('Priority', 'IssuePriorityID');
exports.CPSAttributeMap.set('Date Reported', 'DateReported');
exports.CPSAttributeMap.set('Deadline', 'Deadline');
exports.CPSAttributeMap.set('Submission Date', 'SubmissionDate');
exports.CPSAttributeMap.set('Description', 'Description');
exports.CPSAttributeMap.set('CSH ID', 'IssueID');
exports.CPSAttributeMap.set('Project Name', 'ProjectName');
exports.CPSAttributeMap.set('Contract Name', 'ContractName');
//# sourceMappingURL=CPSAttributes.js.map