export const CSHAttributeMap = new Map()
CSHAttributeMap.set('Category','IssueCategoryID')
CSHAttributeMap.set('Primary Project','PrimaryIprjAutoID')
CSHAttributeMap.set('Primary Contract','PrimaryContractAutoID')
CSHAttributeMap.set('ID', 'IssueID')
CSHAttributeMap.set('Title','Title')
CSHAttributeMap.set('Type','IssueTypeID')
CSHAttributeMap.set('Status','IssueStatusID')
CSHAttributeMap.set('Priority','IssuePriorityID')
CSHAttributeMap.set('Date Reported','DateReported')
CSHAttributeMap.set('Deadline','Deadline')
CSHAttributeMap.set('Submission Date','SubmissionDate')
CSHAttributeMap.set('Description','Description')
CSHAttributeMap.set('CSH ID', 'IssueID')

CSHAttributeMap.set('Project Name','ProjectName')
CSHAttributeMap.set('Contract Name','ContractName')
