export const budgetAttributesMap = new Map()
budgetAttributesMap.set('Fiscal Year', 'FiscalYear')
budgetAttributesMap.set('Associated Project', 'ImplementedProjectAutoID')
budgetAttributesMap.set('Fund', 'FundID')
budgetAttributesMap.set('Department', 'DepartmentID')
budgetAttributesMap.set('Program', 'ProgramID')
budgetAttributesMap.set('District', 'DistrictID')
budgetAttributesMap.set('Currency', 'CurrencyGuid')
budgetAttributesMap.set('Budget Status', 'RelatedStatusID')
budgetAttributesMap.set('Project Name', 'ProjectName')
budgetAttributesMap.set('Fund ID', 'FundID')
budgetAttributesMap.set('Approved Date', 'LatestApprovedDateTime')
budgetAttributesMap.set('Effective Date', 'LatestEffectiveDate')
budgetAttributesMap.set('Budget Status', 'RelatedStatusID')

