export const addAssetAttributeMap = new Map()
addAssetAttributeMap.set('Asset ID', 'assets-assetid')
addAssetAttributeMap.set('Asset Name', 'assets-assetname')
addAssetAttributeMap.set('Asset Type', 'assets-assettypeid')
addAssetAttributeMap.set('Parent Asset','assets-parentassetautoid')
addAssetAttributeMap.set('Asset Status', 'assets-assetstatusid')
addAssetAttributeMap.set('Asset Category', 'assets-nodeid')
addAssetAttributeMap.set('Acquisition Code', 'assets-acquisitioncodeid')
addAssetAttributeMap.set('Acquisition Date', 'assets-acquisitiondate1')
addAssetAttributeMap.set('Placement Date', 'assets-placementdate')
addAssetAttributeMap.set('Description','assets-description')
addAssetAttributeMap.set('Original Value', 'assets-originalvalue')