"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CSHAttributeMap = void 0;
exports.CSHAttributeMap = new Map();
exports.CSHAttributeMap.set('Category', 'IssueCategoryID');
exports.CSHAttributeMap.set('Primary Project', 'PrimaryIprjAutoID');
exports.CSHAttributeMap.set('Primary Contract', 'PrimaryContractAutoID');
exports.CSHAttributeMap.set('ID', 'IssueID');
exports.CSHAttributeMap.set('Title', 'Title');
exports.CSHAttributeMap.set('Type', 'IssueTypeID');
exports.CSHAttributeMap.set('Status', 'IssueStatusID');
exports.CSHAttributeMap.set('Priority', 'IssuePriorityID');
exports.CSHAttributeMap.set('Date Reported', 'DateReported');
exports.CSHAttributeMap.set('Deadline', 'Deadline');
exports.CSHAttributeMap.set('Submission Date', 'SubmissionDate');
exports.CSHAttributeMap.set('Description', 'Description');
exports.CSHAttributeMap.set('CSH ID', 'IssueID');
exports.CSHAttributeMap.set('Project Name', 'ProjectName');
exports.CSHAttributeMap.set('Contract Name', 'ContractName');
//# sourceMappingURL=CSHAttributes.js.map