"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CSPAttributeMap = void 0;
exports.CSPAttributeMap = new Map();
exports.CSPAttributeMap.set('Category', 'IssueCategoryID');
exports.CSPAttributeMap.set('Primary Project', 'PrimaryIprjAutoID');
exports.CSPAttributeMap.set('Primary Contract', 'PrimaryContractAutoID');
exports.CSPAttributeMap.set('ID', 'IssueID');
exports.CSPAttributeMap.set('Title', 'Title');
exports.CSPAttributeMap.set('Type', 'IssueTypeID');
exports.CSPAttributeMap.set('Status', 'IssueStatusID');
exports.CSPAttributeMap.set('Priority', 'IssuePriorityID');
exports.CSPAttributeMap.set('Date Reported', 'DateReported');
exports.CSPAttributeMap.set('Deadline', 'Deadline');
exports.CSPAttributeMap.set('Submission Date', 'SubmissionDate');
exports.CSPAttributeMap.set('Description', 'Description');
exports.CSPAttributeMap.set('CSH ID', 'IssueID');
exports.CSPAttributeMap.set('Project Name', 'ProjectName');
exports.CSPAttributeMap.set('Contract Name', 'ContractName');
//# sourceMappingURL=CSPAttributes.js.map